Front 98
Code-the-Dream-School/bb-practicum-team1-front pull request #111
Opened 2023-05-01 22:44 UTC by koral14

2023-05-02 00:10 UTC, SimonjShurety approved these changes
Nice work. Approved.

2023-05-02 01:31 UTC, SimonjShurety approved these changes
Approved.

2023-05-03 00:16 UTC, cecerodrgz requested changes
Can we delete the unused code on HomePage? 
Also, the pictures for the books aren't loading, is that something we could fix or is that the backend team?
Before merging, can you fix the merging conflicts on App.js? 
Thank you!!

2023-05-03 00:55 UTC, cecerodrgz approved these changes

2023-05-03 01:06 UTC, merged