Front 39-B
Code-the-Dream-School/bb-practicum-team1-front pull request #117
Opened 2023-05-03 11:21 UTC by SimonjShurety

2023-05-04 00:06 UTC, koral14 reviewed
I can see that you added the ProtectedRoute back. Great job, Simon!

2023-05-04 00:06 UTC, koral14 approved these changes
I can see that you added the ProtectedRoute back. Great job, Simon!

2023-05-04 01:43 UTC, Ekaterina-Bondareva requested changes
Could you please resolve merge conflict before I will review this ticket? It will help us to avoid errors. TIA!

2023-05-05 02:56 UTC, Ekaterina-Bondareva approved these changes

2023-05-05 02:58 UTC, merged