Front ticket 36
Code-the-Dream-School/bb-practicum-team1-front pull request #53
Opened 2023-04-12 14:56 UTC by cecerodrgz

I am having issues with the keys on BookItem and bookList, also the pagination isn't showing just yet, would appreciate some guidance on this. Thank you!

2023-04-12 15:54 UTC, jpremo commented on src/components/BookItem/BookItem.js
> +        </>
Pagination should not be inside of BookItem here. BookItem should be inside of Pagination. I would revert the changes to BookItem and just place Pagination directly on a route to test.

2023-04-12 15:54 UTC, jpremo commented on src/components/PagePagination/Pagination.js
> +    className
I would recommend taking in a list of books as a prop. It can be called bookList. See Home.js for an example of what a bookList could look like.

2023-04-12 15:54 UTC, jpremo commented on src/components/PagePagination/Pagination.js
> +    </ul>
Before making the page options, render out bookList. For each item in bookList we can render out a BookItem.

2023-04-14 00:29 UTC, cecerodrgz commented
I fixed the issues that I had, right now it is displaying multiple books and these are only as examples, we can add the ones we are going to use later.

2023-04-14 02:43 UTC, Ekaterina-Bondareva commented
I see the following error when running app from your branch
`Module not found: Error: Can't resolve 'classnames' in '/Users/ekaterinabondareva/Desktop/CTD/Practicum/Book_app/bb-practicum-team1-front/src/components/PagePagination'`
If you added new module could you please also add it to package.json and commit that change in package.json?

2023-04-14 03:14 UTC, Ekaterina-Bondareva requested changes
Nice job Cecilia! 

I see the following error when running app from your branch
Module not found: Error: Can't resolve 'classnames' in '/Users/ekaterinabondareva/Desktop/CTD/Practicum/Book_app/bb-practicum-team1-front/src/components/PagePagination'
If you added new module could you please also add it to package.json and commit that change in package.json?

2023-04-15 17:44 UTC, Ekaterina-Bondareva requested changes
Could you please fix imports in App.js file. Looks like you doubled imports in App.js file when solved merge conflict. Now we have couple same imports there.

2023-04-17 15:56 UTC, Ekaterina-Bondareva requested changes

2023-04-17 15:56 UTC, Ekaterina-Bondareva commented on src/components/HomePage/HomePage.js
> +            <BookList bookList={booklist} />
When I run application I have an error: `ERROR in [eslint] 
src/components/HomePage/HomePage.js
  Line 52:33:  'booklist' is not defined  no-undef
Search for the keywords to learn more about each error.`
Could you please delete line 52?

2023-04-20 03:16 UTC, Ekaterina-Bondareva requested changes
When I start application from your brunch I have 3 errors. 
1. Could you please `line 157` of `HomePage.js`. I suppose it should be `{bookList}` instead of `{booklist}`.
2. In `BookList.js` and `BookItem.js` you have the same problem - you made return part of functional component wrong (close braces wrong, doubled return, etc). Feel free to zoom with me when you will have a time and I will help you to solve it line by line.

2023-04-20 03:16 UTC, Ekaterina-Bondareva commented on src/components/HomePage/HomePage.js
> +            <BookList bookList={booklist} />
Could you please fix line 157. I suppose it should be `{bookList} `instead of `{booklist}`.

2023-04-21 23:55 UTC, closed without merging