Front 38
Code-the-Dream-School/bb-practicum-team1-front pull request #84
Opened 2023-04-24 10:40 UTC by cecerodrgz

I don't have the authentication for the login on my branch, but I wanted to push it so everyone could give it a look.
Still working on it but less work is required.

2023-04-27 01:35 UTC, Ekaterina-Bondareva requested changes
1. Could you please add on Profile Page `all user details (address, firstname, lastname, email).`
2. Could you please use the PaginatedResults component as it was pointed in ticket?

2023-04-30 17:19 UTC, SimonjShurety approved these changes
Approved.

2023-05-01 04:13 UTC, Ekaterina-Bondareva requested changes
ProfilePage always shows data for currently logged in user even if I use /profile/<userId> URL. This component should work differently depending on value of myProfile property.

Also looks like list of books is duplicated because of <BookList> and <PagePagination> tags on lines 36 and 37 in App.js

2023-05-02 20:50 UTC, Ekaterina-Bondareva commented on src/App.js
> +                        <Route path='/profile/:userid' element={<ProfilePage  />} />
Route to /profile/:userId should be removed

2023-05-02 20:51 UTC, Ekaterina-Bondareva commented on src/App.js
> +                        <Route path='/my-profile' element={<ProfilePage myProfile={!!sessionObject}/>}/>
Could you please remove myProfile property as now ProfilePage will always show only my profile?

2023-05-02 20:52 UTC, Ekaterina-Bondareva commented on src/components/ProfilePage/ProfilePage.js
> +const ProfilePage = ({myProfile = false}) => {
Could you please remove `myProfile` property as it is not used?

2023-05-02 20:53 UTC, Ekaterina-Bondareva commented on src/components/ProfilePage/ProfilePage.js
> +    console.log(sessionObject)
Could you please remove this log statement before merging PR?

2023-05-03 03:37 UTC, Ekaterina-Bondareva approved these changes

2023-05-03 03:38 UTC, merged